- ruby-full/Rakefile
- ruby/Rakefile
* renamed biuld[version] task to build:ruby[version]
* add build:all task (invokes build:ruby[2.0.0-p598], build:ruby[2.1.5], build:ruby[2.1.5])
* sign binary file on build[version] task
> ruby, ruby-full: sign binary file, and add build:all task

- ruby/build/scripts/01-setup
- spec/ruby/00base_spec.rb
ref:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838234
- https://release.debian.org/transitions/html/readline7.html
- https://tracker.debian.org/pkg/readline
- https://tracker.debian.org/news/802108
- https://tracker.debian.org/pkg/readline6
- https://tracker.debian.org/news/802379
> readline7 transition

- debian/Rakefile
- spec/baseimage/00base_spec.rb
see also:
- https://wiki.debian.org/UsrMerge
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839046
- https://tracker.debian.org/pkg/usrmerge
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841666
> debian: no-merged-usr

- rails4/build/scripts/01-setup
- rails5/build/scripts/01-setup
- ruby-full/build/scripts/02-rbenv
- tdiary/build/scripts/01-setup
see also: minimum2scp/ruby-binary#70, minimum2scp/ruby-binary#71
> ruby-full, rails4, rails5, tdiary: fixed build error with latest ruby-binary install.sh script

- es-kibana/build/scripts/01-setup
see also:
- https://lists.debian.org/debian-devel/2017/06/msg00375.html
- https://lists.debian.org/debian-devel/2017/06/msg00410.html
> Removed apt-transport-https package from sid

- es-kibana/README.md
- es-kibana/build/scripts/01-setup
ref:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
- https://www.elastic.co/guide/en/kibana/6.0/deb.html
> es-kibana: Elasticsearch 6.0.0, Kibana 6.0.0

- ci-build.dig
- fluentd-ui/Dockerfile
- fluentd-ui/README.md
- fluentd-ui/build/opt/fluentd-ui/start_server.sh
- spec/fluentd-ui/00base_spec.rb
> fluentd-ui: fix puma bind errror

- tdiary/build/home/debian/go/src/github.com/tdiary/tdiary-core/Gemfile.local
- tdiary/build/user-scripts/setup-tdiary.sh
> tdiary: update faraday gem dependency

- baseimage/build/etc/apt/sources.list
- baseimage/build/scripts/01-setup
- spec/baseimage/00base_spec.rb
This reverts commit 0f823699bd71a0a522526b7c96e2e7e140c1c188. (#347)
> Revert "Workaround for building baseimage"

- spec/tdiary/00base_spec.rb
- tdiary/build/home/debian/go/src/github.com/tdiary/tdiary-core/Gemfile.local
> tdiary: removed workaround

- .dependabot/config.yml
ref: https://dependabot.com/blog/introducing-config-files/
> Added Dependabot config file

- .circleci/config.yml
ref: Reusing Config https://circleci.com/docs/2.0/reusing-config/
> Defined "build" as a reusable command (Circle CI 2.1)

- spec/baseimage-stretch/00base_spec.rb
- spec/baseimage/00base_spec.rb
> baseimage, baseimage-stretch: spec for env var INSTALL_DOCKER_CE_CLI=yes

- .github/workflows/ci.yml
https://github.com/actions/cache/releases/tag/v1.0.1
> Updated actions/cache to v1.0.1

- tdiary/build/user-scripts/setup-tdiary.sh
Reverts minimum2scp/dockerfiles#632
> Revert "tdiary: Update octokit gem in Gemfile.lock before bundle install"

- rails6/build/scripts/01-setup
https://hackmd.io/@mametter/mimemagic-info-ja
> rails6: fixed build error (mimemagic gem depends shared-mime-info package)

- tdiary/build/home/debian/tdiary/start.sh
- tdiary/build/user-scripts/setup-tdiary.sh
> tdiary: Launch rack app server by rackup

- rails6/build/scripts/01-setup
- ruby-full/build/scripts/02-rbenv
- spec/ruby-full/00base_spec.rb
- tdiary/build/scripts/01-setup
- ruby-full: install latest ruby-binary (rubygems 3.2.19, bundler 2.2.19)
- rails6: install latest ruby-binary (rubygems 3.2.19, bundler 2.2.19)
- tdiary: install latest ruby-binary (rubygems 3.2.19, bundler 2.2.19)
> ruby-full, rails6, tdiary: install latest ruby-binary (rubygems 3.2.19, bundler 2.2.19)

- nodejs/README.md
- nodejs/build/scripts/02-nodenv
- rails6/build/scripts/02-nodenv
- spec/nodejs/00base_spec.rb
- spec/rails6/00base_spec.rb
- nodejs: updated nodejs version to 16.3.0
- rails6: updated nodejs version to 16.3.0
> nodejs, rails6: nodejs 16.3.0

- es-kibana/README.md
- es-kibana/build/scripts/01-setup
- es-kibana: Elasticsearch 7.13.1, Kibana 7.13.1
- es-kibana: updated README.md
> es-kibana: Elasticsearch 7.13.1, Kibana 7.13.1

- rails6/build/scripts/01-setup
- ruby-full/build/scripts/02-rbenv
- spec/ruby-full/00base_spec.rb
- tdiary/build/scripts/01-setup
- ruby-full: install latest ruby-binary (rubygems 3.2.20, bundler 2.2.20)
- rails6: install latest ruby-binary (rubygems 3.2.20, bundler 2.2.20)
- tdiary: install latest ruby-binary (rubygems 3.2.20, bundler 2.2.20)
> ruby-full, rails6, tdiary: install latest ruby-binary (rubygems 3.2.20, bundler 2.2.20)

- es-kibana/README.md
- es-kibana/build/scripts/01-setup
- es-kibana: Elasticsearch 7.13.2, Kibana 7.13.2
- es-kibana: updated README.md
> es-kibana: Elasticsearch 7.13.2, Kinaba 7.13.2

- nodejs/README.md
- spec/nodejs/00base_spec.rb
- spec/rails6/00base_spec.rb
- nodejs: nodejs 16.4.0
- rails6: nodejs 16.4.0
> nodejs, rails6: nodejs 16.4.0

- rails6/build/scripts/01-setup
- ruby-full/build/scripts/02-rbenv
- spec/ruby-full/00base_spec.rb
- tdiary/build/scripts/01-setup
- ruby-full: install latest ruby-binary (rubygems 3.2.21, bundler 2.2.21)
- rails6: install latest ruby-binary (rubygems 3.2.21, bundler 2.2.21)
- tdiary: install latest ruby-binary (rubygems 3.2.21, bundler 2.2.21)
> ruby-full, rails6, tdiary: install latest ruby-binary (rubygems 3.2.21, bundler 2.2.21)

- nodejs/README.md
- spec/nodejs/00base_spec.rb
- spec/rails6/00base_spec.rb
- nodejs: updated nodejs version to 16.4.1
- rails6: updated nodejs version to 16.4.1
> nodejs, rails6: nodejs 16.4.1

- rails7/build/scripts/01-setup
- ruby-full/build/scripts/02-rbenv
- spec/rails7/00base_spec.rb
- spec/ruby-full/00base_spec.rb
- spec/tdiary/00base_spec.rb
- tdiary/build/scripts/01-setup
- ruby-full: ruby 3.2.0, 3.1.3, 3.0.5, 2.7.7 / rubygems 3.4.1, bundler 2.4.1
- rails7: ruby 3.2.0
- tdiary: ruby 3.2.0
> ruby-full, rails7, tdiary: ruby 3.2.0, rubygems 3.4.1, bundler 2.4.1

- baseimage-stretch/build/etc/apt/sources.list
- baseimage-stretch/build/opt/init-wrapper/pre-init.d/05-apt
- spec/baseimage-stretch/00base_spec.rb
https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html
> baseimage-stretch: Updated apt-line to use archive.debian.org
