minimum2scp/dockerfiles

baseimage-wheezy/build/opt/init-wrapper/pre-init.d/10-save-env
baseimage/build/opt/init-wrapper/pre-init.d/10-save-env

before this commit:
```
% docker run -e FOO="a \"b\" 'c'" -d --name before minimum2scp/baseimage:latest
7aefa5676ed5cd63e3db656a80d6c0a7025813691c8796fe805d85666f669d58
% docker exec before cat /etc/profile.d/00docker-env.sh
export FOO=a "b" 'c'
% docker exec before sh -c 'echo $FOO'
a "b" 'c'
% docker exec before sh -lc 'echo $FOO'
a
```
after this commit:
```
% docker run -e FOO="a \"b\" 'c'" -d --name after minimum2scp/baseimage:next
0e7a6f32c742b592d1a8261b889ca043f15bd69c1f2a91ae93b4ad4b00824795
% docker exec after cat /etc/profile.d/00docker-env.sh
export FOO='a "b" '"'"'c'"'"
% docker exec after sh -c 'echo $FOO'
a "b" 'c'
% docker exec after sh -lc 'echo $FOO'
a "b" 'c'
```

baseimage, baseimage-wheezy: quote env vars in /etc/profile.d/00docker-env.sh by `export -p`

---

tdiary/build/user-scripts/setup-tdiary.sh

fix build error
```
+ bash -l -c cd ~; rbenv local 2.2.0
rbenv: version `2.2.0' not installed
```

tdiary: use Ruby 2.2.1

---

sphinx/build/scripts/01-setup

```
+ pip install sphinxjp.themecore sphinxjp.themes.sphinxjp sphinx_rtd_theme
Collecting sphinxjp.themecore
Downloading sphinxjp.themecore-0.2.0.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: No module named setuptools
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mMoOEL/sphinxjp.themecore
```

sphinx: fixed build error while `pip install sphinxjp.themecore ...`

---

Gemfile
Gemfile.lock

```
/usr/lib/ruby/vendor_ruby/bundler/rubygems_integration.rb:304:in `block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
from /home/tsuyoshi/go/src/github.com/minimum2scp/dockerfiles/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
rake aborted!
```

Added rake into Gemfile

---

ruby-full/build/scripts/01-setup

Fixed build problem:
```
+ apt-get install -y --no-install-recommends ruby2.2 ruby2.2-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ruby2.2
E: Couldn't find any package by glob 'ruby2.2'
E: Couldn't find any package by regex 'ruby2.2'
E: Unable to locate package ruby2.2-dev
E: Couldn't find any package by glob 'ruby2.2-dev'
E: Couldn't find any package by regex 'ruby2.2-dev'
```

ruby-full: do not install ruby2.2

---

rails4/build/scripts/01-setup

https://hub.docker.com/r/minimum2scp/rails4/builds/b6fnxiusdcrgcuq3bkrtmu7/

rails4: Do not install rails 4.x gem for ruby 2.4.0-preview2

---

rails4/build/scripts/01-setup

```
+ bash -lc RBENV_VERSION=2.4.0-preview3 gem install -N rails --version '~> 4.0'
(snip)
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
ERROR: Failed to build gem native extension.
current directory: /opt/rbenv/versions/2.4.0-preview3/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/opt/rbenv/versions/2.4.0-preview3/bin/ruby -r ./siteconf20161111-7096-1htyjzy.rb extconf.rb
creating Makefile
current directory: /opt/rbenv/versions/2.4.0-preview3/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean
current directory: /opt/rbenv/versions/2.4.0-preview3/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function 'generate_json':
generator.c:861:25: …
```

rails4: Do not install rails 4.x gem for ruby 2.4.0-preview3

---

rails4/build/scripts/01-setup

```
+ bash -lc RBENV_VERSION=2.4.0-rc1 gem install -N rails --version '~> 4.0'
(snip)
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
ERROR: Failed to build gem native extension.
current directory: /opt/rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/opt/rbenv/versions/2.4.0-rc1/bin/ruby -r ./siteconf20161214-6695-1w3bidu.rb extconf.rb
creating Makefile
current directory: /opt/rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean
current directory: /opt/rbenv/versions/2.4.0-rc1/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function 'generate_json':
generator.c:861:25: error: 'rb_cFixnum' …
```

rails4: Do not install rails 4.x gem for ruby 2.4.0-rc1

---

fluentd-ui/build/scripts/01-setup

```
+ curl -L https://td-toolbelt.herokuapp.com/sh/install-debian-jessie-td-agent2.sh
+ sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   551  100   551    0     0    232      0  0:00:02  0:00:02 --:--:--   232
This script requires superuser access to install apt packages.
You will be prompted for your password by sudo.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
100  3157  100  3157    0     0  19062      0 --:--:-- --:--:-- --:--:-- 19133
(23) Failed …
```

fluentd-ui: fixed build error (installed gnupg, dirmngr packages)

---

squid/README.md

Fix `htpt://` and replace with `http://` in proxy environment variable example.

squid: minor typo correction in readme

---

ruby-full/README.md
spec/ruby-full/00base_spec.rb
spec/ruby/00base_spec.rb

ruby-defaults 1:2.5.0
https://tracker.debian.org/news/937912
ruby2.5 2.5.0-6
https://tracker.debian.org/news/937877
transition: ruby2.5
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888531
https://release.debian.org/transitions/html/ruby2.5.html

ruby, ruby-full: Fixed spec (ruby2.5 transition)

---

tdiary/build/user-scripts/setup-tdiary.sh

Workaround for build error:
```
Bundler could not find compatible versions for gem "faraday":
In snapshot (Gemfile.lock):
faraday (= 0.14.0)
In Gemfile:
tdiary-contrib was resolved to 5.0.8, which depends on
pushbullet_ruby was resolved to 1.1.1, which depends on
faraday (~> 0.9.0)
octokit was resolved to 4.8.0, which depends on
sawyer (>= 0.5.3, ~> 0.8.0) was resolved to 0.8.1, which depends on
faraday (< 1.0, ~> 0.8)
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

tdiary: fixed build error

---

baseimage/build/etc/apt/sources.list
baseimage/build/scripts/01-setup
spec/baseimage/00base_spec.rb

Building baseimage failed:
```console
% docker build --no-cache -t minimum2scp/baseimage:latest baseimage
Sending build context to Docker daemon  221.7kB
Step 1/7 : FROM minimum2scp/debian:latest
---> 38d941937d0b
Step 2/7 : MAINTAINER YAMADA Tsuyoshi tyamada@minimum2scp.org
---> Running in b2cad4391d32
Removing intermediate container b2cad4391d32
---> 525c960cb818
Step 3/7 : COPY build /tmp/build/baseimage
---> 9150b28f96fb
Step 4/7 : RUN run-parts --report --exit-on-error /tmp/build/baseimage/scripts && rm -rfv /tmp/build
---> Running in 2e9dcba6e139
...(snip)...
+ apt-get install -y --no-install-recommends --auto-remove --purge sudo adduser curl ca-certificates openssl git lv vim-tiny man-db whiptail zsh net-tools unzip etckeeper locales tzdata localepurge sysvinit-core systemd-sysv- …
```

Workaround for building baseimage

---

spec/ruby/00base_spec.rb

bundler 1.16.1-2 package was uploaded to sid
https://tracker.debian.org/news/954421/accepted-bundler-1161-2-source-into-unstable/

ruby: fixed spec

---

tdiary/build/scripts/01-setup

`docker build` -> `bundle install` failed.
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/home/debian/go/src/github.com/tdiary/tdiary-core/vendor/bundle/ruby/2.5.0/gems/idn-ruby-0.1.0/ext
/opt/rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180610-11470-g9dvht.rb
extconf.rb
checking for -lidn... no
ERROR: could not find idn library!
Please install the GNU IDN library or alternatively specify at least one
of the following options if the library can only be found in a non-standard
location:
--with-idn-dir=/path/to/non/standard/location
or
--with-idn-lib=/path/to/non/standard/location/lib
--with-idn-include=/path/to/non/standard/location/include
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary …
```

tdiary: Install libidn11-dev to fix bundle install error

---

debian-jessie/Rakefile

--cache-dir is added when DEBOOTSTRAP_CACHE_DIR is given.
see also: #363

Removed unnecessary --cache-dir option 

---

debian-jessie/Rakefile
debian-stretch/Rakefile
debian/Rakefile

docker-ce 18.09.0 does not install mkimage.sh script.

Fixed mkimage.sh search path

---

ruby-full/README.md
ruby-full/build/scripts/02-rbenv
ruby-stretch/build/scripts/01-setup
ruby/build/scripts/01-setup
spec/ruby-full/00base_spec.rb
spec/ruby-stretch/00base_spec.rb
spec/ruby/00base_spec.rb

openssl1.0 was removed from sid
https://tracker.debian.org/news/1033424/removed-102q-2-from-unstable/

ruby, ruby-full, ruby-stretch: openssl 1.0 -> 1.1

---

baseimage/build/opt/init-wrapper/pre-init.d/99-install-post-init

Fix CI failures
<details>
```console
% bundle exec rspec spec/baseimage/00base_spec.rb 
minimum2scp/baseimage
with env [APT_LINE=keep]
(...snip...)
with env [APT_LINE=keep, INSTALL_NGINX=yes]
File "/opt/init-wrapper/post-init.d/07-nginx"
example at ./spec/baseimage/00base_spec.rb:325 (FAILED - 1)
File "/etc/apt/sources.list.d/nginx.list"
example at ./spec/baseimage/00base_spec.rb:329 (FAILED - 2)
File "/etc/apt/trusted.gpg.d/nginx.gpg"
example at ./spec/baseimage/00base_spec.rb:333 (FAILED - 3)
File "/etc/apt/preferences.d/nginx"
example at ./spec/baseimage/00base_spec.rb:337 (FAILED - 4)
Command "apt-cache policy"
stdout
example at ./spec/baseimage/00base_spec.rb:341 (FAILED - 5)
stdout
example at ./spec/baseimage/00base_spec.rb:346 (FAILED - 6)
Package "nginx"
example at …
```

baseimage: fixed to invoke post init scripts

---

.github/workflows/ci.yml

Reverts minimum2scp/dockerfiles#570
----
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses
> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

Revert "Updated actions/cache to v1.0.1"

---

tdiary/build/home/debian/go/src/github.com/tdiary/tdiary-core/Gemfile.local
tdiary/build/user-scripts/setup-tdiary.sh

```
+ bash -l -c bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "faraday":
In snapshot (Gemfile.lock):
faraday (= 1.0.0)
In Gemfile:
octokit was resolved to 4.15.0, which depends on
faraday (>= 0.9)
tdiary-contrib was resolved to 5.1.0, which depends on
pushbullet_ruby was resolved to 1.1.1, which depends on
faraday (~> 0.9.0)
octokit was resolved to 4.15.0, which depends on
sawyer (~> 0.8.0, >= 0.5.3) was resolved to 0.8.2, which depends on
faraday (> 0.8, < 2.0)
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
run-parts: …
```

tdiary: workaround for build error (downgrade faraday gem version)

---

ruby-full/README.md
spec/ruby-full/00base_spec.rb
spec/ruby/00base_spec.rb

ruby-defaults 1:2.7
https://lists.debian.org/debian-devel-changes/2020/03/msg01944.html
transition: ruby2.5-rm
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953881
https://release.debian.org/transitions/html/ruby2.5-rm.html

ruby, ruby-full: Fixed spec, switched to ruby2.7 (ruby2.5-rm transition)

---

ruby-full/README.md
spec/ruby-full/00base_spec.rb
spec/ruby/00base_spec.rb

ruby2.7 2.7.1-1
https://tracker.debian.org/news/1142056/accepted-ruby27-271-1-source-into-unstable/

ruby, ruby-full: Fixed spec (ruby 2.7.1)

---

norikra/build/scripts/02-rbenv
spec/norikra/00base_spec.rb

Fixes build error:
```
+ bash -l -c RBENV_VERSION=jruby-9.1.5.0 gem install norikra
unsupported Java version "11", defaulting to 1.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
io/console on JRuby shells out to stty for most operations
Successfully installed erubis-2.7.0
Successfully installed rack-2.2.3
Successfully installed tilt-2.0.10
Successfully installed rack-protection-2.0.8.1
Successfully …
```

norikra: jruby 9.2.11.1

---

spec/ruby-buster/00base_spec.rb

bundler 1.17.3-3+deb10u1 is uploaded
https://tracker.debian.org/news/1146126/accepted-bundler-1173-3deb10u1-source-into-proposed-updates-stable-new-proposed-updates/

Fixed ruby-buster spec

---

rails6/build/scripts/01-setup

Reverts minimum2scp/dockerfiles#777
https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/

Revert "rails6: fixed build error (mimemagic gem depends shared-mime-info package)"

---

baseimage-buster/build/opt/custom-installers/nginx/install.sh
baseimage-stretch/build/opt/custom-installers/nginx/install.sh
baseimage/build/opt/custom-installers/nginx/install.sh
spec/baseimage-buster/00base_spec.rb
spec/baseimage-stretch/00base_spec.rb
spec/baseimage/00base_spec.rb

apt-key is deprecated.
see also: https://wiki.debian.org/DebianRepository/UseThirdParty

baseimage, baseimage-buster, baseimage-stretch: replaced apt-key command in nginx installer script

---

.github/workflows/ci.yml
.github/workflows/ci.yml.erb

https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
https://docs.github.com/en/actions/guides/about-continuous-integration#skipping-workflow-runs

GitHub Actions has built-in support for `[ci skip]` keyword

---

baseimage/build/scripts/01-setup

see also:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998340
- https://tracker.debian.org/news/1273532/accepted-orphan-sysvinit-scripts-008-source-into-unstable/
- https://tracker.debian.org/news/1274713/accepted-rsyslog-821100-2-source-into-unstable/
close #887

baseimage: install orphan-sysvinit-scripts package to run rsyslog with sysv init

---

baseimage-bullseye/Rakefile
baseimage-buster/Rakefile
baseimage-stretch/Rakefile
baseimage/Rakefile
debian-bullseye/Rakefile
debian-buster/Rakefile
debian-stretch/Rakefile
debian/Rakefile

- "warning: Passing safe_level with the 2nd argument of ERB.new is
deprecated. Do not use it, and specify other arguments as keyword
arguments."
- "warning: Passing trim_mode with the 3rd argument of ERB.new is
deprecated. Use keyword argument like ERB.new(str, trim_mode: ...)
instead."

Addressed ERB.new arguments warnings

---

spec/ruby-full/00base_spec.rb
spec/ruby/00base_spec.rb

openssl 3.0 transition:
https://tracker.debian.org/news/1324692/accepted-openssl-303-2-source-into-unstable/
https://release.debian.org/transitions/html/auto-openssl.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995636
ruby3.0 package have openssl 3.0 patch since 3.0.2-6:
https://tracker.debian.org/news/1296502/accepted-ruby30-302-6-source-into-unstable/

ruby: fixed spec (openssl 3.0 transition)

---

baseimage/build/opt/custom-installers/nginx/install.sh
spec/baseimage/00base_spec.rb
spec/nodejs/00base_spec.rb
spec/rails7/00base_spec.rb
spec/ruby/00base_spec.rb
spec/tdiary/00base_spec.rb
tdiary/build/scripts/01-setup

nginx pre-built binary for debian bullseye is built against libssl1.1,
but libssl1.1 is not available on debian sid.
<details>
```console
% docker run --rm --entrypoint /bin/sh minimum2scp/baseimage:latest /opt/custom-installers/nginx/install.sh
+ nginx_version=1.22.1-1~bullseye
+ apt-get install -y --no-install-recommends gnupg
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
dirmngr gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server
gpgconf gpgsm libassuan0 libksba8 libnpth0 libreadline8 libsqlite3-0
pinentry-curses readline-common
Suggested packages:
dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage
scdaemon pinentry-doc readline-doc
The following NEW packages …
```

baseimage, tdiary: Switched nginx package to debian.org ones

---

spec/baseimage/00base_spec.rb
spec/tdiary/00base_spec.rb

https://tracker.debian.org/news/1426966/accepted-nginx-1221-8-source-into-unstable/
https://tracker.debian.org/news/1426987/accepted-nginx-1221-9-source-into-unstable/

baseimage, tdiary: nginx 1.22.1-9

---

spec/baseimage/00base_spec.rb
spec/tdiary/00base_spec.rb

https://tracker.debian.org/news/1440028/accepted-nginx-1240-1-source-into-unstable/

baseimage, tdiary: nginx 1.24.0-1
